# Numpy

Numpy is a fundemental package for scientific computing in python

In [1]:
#importing the library
import numpy as np

Numpy array : It is a homogeneous collection of elements of same datatype

In [4]:
#how to create an array
a = np.array([1,2,3])  # this is a 1-dimensional array
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
#2D array : it will be enclosed within a [[]]
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
#3d array
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
# dtype : we can change the datatype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [9]:
# we can create an array using arange(start,stop,step)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [10]:
# reshape : used to change the dimension 
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [11]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
# np.zeros - a array with full of zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
#np.ones - an array with ones
np.ones((2,2),dtype = int)

array([[1, 1],
       [1, 1]])

In [17]:
#random() : creates an array with values range between 0 and 1
np.random.random((3,4))

array([[0.41122712, 0.22873552, 0.76300336, 0.50741812],
       [0.91042621, 0.36274197, 0.60978681, 0.44872657],
       [0.15250148, 0.20299327, 0.64625604, 0.48790619]])

In [22]:
#linspace : just like the arange linspace(start,stop,len,dtype = '')
np.linspace(1,12,3,dtype = int)

array([ 1,  6, 12])

In [24]:
#np.identity : This will create an identity matrix
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Array attributes

In [31]:
a1 = np.arange(10,dtype = int)
a2 = np.arange(12,dtype=int).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
#ndim : returns the dimesion of the array
a3.ndim

3

In [30]:
#shape : return the shape of the array
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [33]:
#size : no of elements
a2.size

12

In [34]:
#itemsize :  np.itemsize is an attribute of a NumPy array (ndarray) that returns the size (in bytes) of each element in the array.
a2.size

12

In [35]:
#dtype : returns the datatype of the array
a2.dtype

dtype('int64')

### changing the datatype

In [36]:
#astype  : chnage the datatype
a2.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### Array operations

In [38]:
a = np.arange(12).reshape(3,4)
b = np.arange(13,25).reshape(3,4)

scalar operations

In [39]:
a+b

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

In [40]:
a - b

array([[-13, -13, -13, -13],
       [-13, -13, -13, -13],
       [-13, -13, -13, -13]])

In [41]:
a * b

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [42]:
a/b

array([[0.        , 0.07142857, 0.13333333, 0.1875    ],
       [0.23529412, 0.27777778, 0.31578947, 0.35      ],
       [0.38095238, 0.40909091, 0.43478261, 0.45833333]])

In [43]:
a **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [44]:
#relational
a == 11

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

### Array Functions

In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
#max() , axis -> 0 (col) -> 1 (row)
np.max(a,axis=1) 

array([ 3,  7, 11])

In [49]:
#min()
np.min(a,axis=0)

array([0, 1, 2, 3])

In [51]:
#sum()
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [52]:
#prod()
np.prod(a,axis=1)

array([   0,  840, 7920])

In [54]:
#mean()
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [55]:
#median()
np.median(a,axis=1)

array([1.5, 5.5, 9.5])

In [56]:
#std()
np.std(a,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [57]:
#var()
np.var(a,axis=0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [58]:
#sin()
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [61]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [64]:
#log()
np.log(b)

array([[2.56494936, 2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383]])

In [65]:
#exponents
np.exp(b)

array([[4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10]])

In [69]:
#round()
c = np.random.random((3,4))
np.round(c)
np.ceil(c)
np.floor(c)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### indexing and slicing


In [70]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [77]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1[-1]

np.int64(9)

In [79]:
a1[3]

np.int64(3)

In [80]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a2[1,2] # array[row ,column]

np.int64(6)

In [82]:
a2[2,-1]

np.int64(11)

In [83]:
a2[1,0]

np.int64(4)

In [84]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [86]:
a3[1,0,1]

np.int64(5)

In [87]:
a3[0,1,0]

np.int64(2)

In [88]:
a3[0,0,0]

np.int64(0)

In [89]:
a3[1,1,0]

np.int64(6)

In [91]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
#slicing
a1[2:5]

array([2, 3, 4])

In [93]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a2[0,:]

array([0, 1, 2, 3])

In [98]:
a2[:,2]

array([ 2,  6, 10])

In [99]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [105]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [107]:
a[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [110]:
a[1,::3]

array([4, 7])

In [112]:
a[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])